[package]
name = "to_do"
version = "0.1.0"
authors = ["r366y"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
dirs = "5.0.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }

